/**
 * Federal EPA compliance rules per 40 CFR Part 280.
 * Updated per the 2015 UST Rule revision (effective Oct 13, 2015; compliance Oct 13, 2018)
 * and incorporating 2024 amendments where applicable.
 *
 * These are seeded into compliance_rules with stateId: null and ruleSource: 'EPA'.
 *
 * Key citations verified against 40 CFR Part 280:
 * - Walkthrough inspections: 280.36
 * - Spill/overfill/sump testing: 280.35
 * - Release detection: 280.40-280.45
 * - Corrosion protection: 280.31
 * - Operator training: 280.240-280.245
 * - Financial responsibility: 280.90-280.116
 * - Closure: 280.70-280.74
 * - Release response: 280.50-280.67
 */

export interface FederalRule {
  inspectionType: string;
  ruleSource: 'EPA';
  category: 'INSPECTION' | 'TESTING' | 'CERTIFICATION' | 'TRAINING' | 'DOCUMENTATION' | 'REPORTING' | 'FINANCIAL' | 'CLOSURE';
  frequencyMonths: number | null;
  frequencyDays: number | null;
  description: string;
  citation: string;
  equipmentType: string;
  appliesToMaterial: string | null;
  appliesToLeakDetection: string | null;
  appliesToCorrosionProtection: string | null;
  notes: string | null;
}

export const federalRules: FederalRule[] = [
  // ============================================
  // MONTHLY (frequencyMonths: 1)
  // ============================================
  {
    inspectionType: 'EPA_MONTHLY_WALKTHROUGH_SPILL',
    ruleSource: 'EPA',
    category: 'INSPECTION',
    frequencyMonths: 1,
    frequencyDays: null,
    description:
      'Monthly walkthrough inspection: visually check spill prevention equipment (spill buckets/catchment basins) for damage, deterioration, leaks, and obstructions. Added by the 2015 UST rule revision.',
    citation: '40 CFR 280.36(a)(1)(i)',
    equipmentType: 'SPILL_PREVENTION',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'New requirement from 2015 revision. Compliance deadline was Oct 13, 2018.',
  },
  {
    inspectionType: 'EPA_MONTHLY_WALKTHROUGH_RELEASE_DETECTION',
    ruleSource: 'EPA',
    category: 'INSPECTION',
    frequencyMonths: 1,
    frequencyDays: null,
    description:
      'Monthly walkthrough inspection: check release detection equipment is operating with no alarms or unusual readings. Verify monitoring systems are functioning. Added by the 2015 UST rule revision.',
    citation: '40 CFR 280.36(a)(1)(ii)',
    equipmentType: 'RELEASE_DETECTION',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'New requirement from 2015 revision.',
  },
  {
    inspectionType: 'EPA_MONTHLY_RELEASE_DETECTION_MONITORING',
    ruleSource: 'EPA',
    category: 'TESTING',
    frequencyMonths: 1,
    frequencyDays: null,
    description:
      'Monthly release detection monitoring using an approved method: automatic tank gauging (ATG), statistical inventory reconciliation (SIR), interstitial monitoring, vapor monitoring, or groundwater monitoring. Records must be maintained for at least 12 months.',
    citation: '40 CFR 280.41(a)',
    equipmentType: 'RELEASE_DETECTION',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'Method must meet performance standards in 40 CFR 280.43. Manual tank gauging only for tanks ≤2,000 gallons.',
  },
  {
    inspectionType: 'EPA_BIMONTHLY_IMPRESSED_CURRENT_CHECK',
    ruleSource: 'EPA',
    category: 'INSPECTION',
    frequencyMonths: 2,
    frequencyDays: null,
    description:
      'Impressed current cathodic protection systems must be inspected every 60 days to ensure the system is running properly. Check rectifier output readings.',
    citation: '40 CFR 280.31(c)',
    equipmentType: 'CATHODIC_PROTECTION',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: 'CATHODIC_PROTECTION',
    notes: 'Applies specifically to impressed current CP systems, not sacrificial anode systems. Does not apply to fiberglass tanks.',
  },

  // ============================================
  // ANNUAL (frequencyMonths: 12)
  // ============================================
  {
    inspectionType: 'EPA_ANNUAL_WALKTHROUGH_SUMPS',
    ruleSource: 'EPA',
    category: 'INSPECTION',
    frequencyMonths: 12,
    frequencyDays: null,
    description:
      'Annual walkthrough inspection: check under containment sumps (below handhole/manway covers) and inspect hand-held electronic release detection equipment. Added by the 2015 UST rule revision.',
    citation: '40 CFR 280.36(a)(2)',
    equipmentType: 'CONTAINMENT_SUMP',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'New requirement from 2015 revision.',
  },
  {
    inspectionType: 'EPA_ANNUAL_LINE_LEAK_DETECTOR_TEST',
    ruleSource: 'EPA',
    category: 'TESTING',
    frequencyMonths: 12,
    frequencyDays: null,
    description:
      'Annual test of automatic line leak detectors (ALLDs) on pressurized piping to verify detection capability of 3 gallons per hour at 10 psi within 1 hour. New explicit annual testing requirement from 2015 rule revision.',
    citation: '40 CFR 280.44(a)',
    equipmentType: 'LINE_LEAK_DETECTOR',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'Applies to all pressurized piping with ALLDs. New annual testing requirement from 2015 revision.',
  },
  {
    inspectionType: 'EPA_ANNUAL_RELEASE_DETECTION_OPERABILITY',
    ruleSource: 'EPA',
    category: 'TESTING',
    frequencyMonths: 12,
    frequencyDays: null,
    description:
      'Annual operability testing of release detection equipment including tank probes, sensors, and electronic monitoring devices to verify functionality per manufacturer specifications.',
    citation: '40 CFR 280.40(a)(3)',
    equipmentType: 'RELEASE_DETECTION',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: null,
  },
  {
    inspectionType: 'EPA_ANNUAL_FINANCIAL_RESPONSIBILITY',
    ruleSource: 'EPA',
    category: 'FINANCIAL',
    frequencyMonths: 12,
    frequencyDays: null,
    description:
      'Annual review and maintenance of financial responsibility documentation. Must demonstrate coverage of at least $1 million per occurrence. Mechanisms include insurance, surety bond, guarantee, letter of credit, state fund, or self-insurance.',
    citation: '40 CFR 280.90-280.116',
    equipmentType: 'FINANCIAL',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: '$1M per occurrence / $1M aggregate for 1-100 petroleum USTs; $1M per occurrence / $2M aggregate for 101+ USTs.',
  },

  // ============================================
  // TRIENNIAL (frequencyMonths: 36)
  // ============================================
  {
    inspectionType: 'EPA_TRIENNIAL_SPILL_EQUIPMENT_TEST',
    ruleSource: 'EPA',
    category: 'TESTING',
    frequencyMonths: 36,
    frequencyDays: null,
    description:
      'Test spill prevention equipment (spill buckets/catchment basins) at least every 3 years to ensure they are liquid-tight. Testing per PEI RP1200 or manufacturer specifications. Alternative: double-walled spill buckets with interstitial monitoring may use monitoring in lieu of testing.',
    citation: '40 CFR 280.35(a)(1)',
    equipmentType: 'SPILL_PREVENTION',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'New requirement from 2015 revision. Double-walled spill buckets with interstitial monitoring exempt per 280.35(a)(1)(ii).',
  },
  {
    inspectionType: 'EPA_TRIENNIAL_OVERFILL_EQUIPMENT_INSPECTION',
    ruleSource: 'EPA',
    category: 'TESTING',
    frequencyMonths: 36,
    frequencyDays: null,
    description:
      'Inspect overfill prevention equipment at least every 3 years. Flow restriction devices (ball float valves) must be inspected for proper operation. Electronic/mechanical shutoff devices must be tested to ensure activation at proper tank level (90% for shutoff, 95% for alarm).',
    citation: '40 CFR 280.35(a)(2)',
    equipmentType: 'OVERFILL_PREVENTION',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'New requirement from 2015 revision.',
  },
  {
    inspectionType: 'EPA_TRIENNIAL_CONTAINMENT_SUMP_TEST',
    ruleSource: 'EPA',
    category: 'TESTING',
    frequencyMonths: 36,
    frequencyDays: null,
    description:
      'Test containment sumps used for interstitial monitoring of piping every 3 years to ensure they are liquid-tight. Testing must verify sump integrity.',
    citation: '40 CFR 280.35(b)',
    equipmentType: 'CONTAINMENT_SUMP',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'New requirement from 2015 revision. Applies only to sumps used for interstitial monitoring.',
  },
  {
    inspectionType: 'EPA_TRIENNIAL_CP_SURVEY',
    ruleSource: 'EPA',
    category: 'TESTING',
    frequencyMonths: 36,
    frequencyDays: null,
    description:
      'Comprehensive cathodic protection system survey by a qualified cathodic protection tester every 3 years. Must evaluate entire CP system including anodes, rectifiers, test stations, and confirm adequate protection levels (minimum -850mV).',
    citation: '40 CFR 280.31(b)',
    equipmentType: 'CATHODIC_PROTECTION',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: 'CATHODIC_PROTECTION',
    notes: 'Must be tested within 6 months of installation and every 3 years thereafter.',
  },
  {
    inspectionType: 'EPA_TRIENNIAL_CLASS_A_TRAINING',
    ruleSource: 'EPA',
    category: 'TRAINING',
    frequencyMonths: 36,
    frequencyDays: null,
    description:
      'Class A operator training renewal. Class A operators (owners/senior management) must broadly understand UST regulatory requirements and must complete retraining every 3 years or within 30 days of a facility failing a compliance inspection.',
    citation: '40 CFR 280.242, 280.245',
    equipmentType: 'OPERATOR',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'New Subpart J added by 2015 revision. Retraining also triggered within 30 days of significant non-compliance.',
  },
  {
    inspectionType: 'EPA_TRIENNIAL_CLASS_B_TRAINING',
    ruleSource: 'EPA',
    category: 'TRAINING',
    frequencyMonths: 36,
    frequencyDays: null,
    description:
      'Class B operator training renewal. Class B operators (facility/site managers) implement day-to-day UST compliance and must complete retraining every 3 years or within 30 days of a facility failing a compliance inspection.',
    citation: '40 CFR 280.243, 280.245',
    equipmentType: 'OPERATOR',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'New Subpart J added by 2015 revision.',
  },

  // ============================================
  // FIVE-YEAR / TEN-YEAR (frequencyMonths: 60/120)
  // ============================================
  {
    inspectionType: 'EPA_INTERNAL_LINING_INSPECTION',
    ruleSource: 'EPA',
    category: 'INSPECTION',
    frequencyMonths: 60,
    frequencyDays: null,
    description:
      'Internally lined steel tanks must be inspected within 10 years of lining and every 5 years thereafter to verify the lining is intact and functioning as designed. Must meet NACE RP-02 or equivalent.',
    citation: '40 CFR 280.21(b)(2)',
    equipmentType: 'TANK',
    appliesToMaterial: 'STEEL',
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: 'INTERNAL_LINING',
    notes: 'Applies only to steel tanks using internal lining as the sole method of corrosion protection.',
  },
  {
    inspectionType: 'EPA_STEEL_TANK_UT_THICKNESS_TEST',
    ruleSource: 'EPA',
    category: 'TESTING',
    frequencyMonths: 120,
    frequencyDays: null,
    description:
      'Ultrasonic thickness (UT) evaluation recommended for steel tanks over 25 years old to assess wall integrity and remaining service life. Industry standard per STI SP001 and PEI RP100. Identifies thinning from external corrosion even with CP in place.',
    citation: '40 CFR 280.21; STI SP001-19',
    equipmentType: 'TANK',
    appliesToMaterial: 'STEEL',
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'Not explicitly mandated by EPA but required by many states and insurers for tanks >25 years. Recommended every 10 years after initial assessment.',
  },
  {
    inspectionType: 'EPA_FIBERGLASS_TANK_INTEGRITY_INSPECTION',
    ruleSource: 'EPA',
    category: 'INSPECTION',
    frequencyMonths: 120,
    frequencyDays: null,
    description:
      'Periodic integrity assessment of fiberglass (FRP) tanks to check for osmotic blistering, structural degradation, and laminate delamination. Per manufacturer recommendations and UL 1316 standards. Especially important for tanks >20 years old.',
    citation: '40 CFR 280.21(b)(1); UL 1316',
    equipmentType: 'TANK',
    appliesToMaterial: 'FIBERGLASS',
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: 'FIBERGLASS_NO_CP_NEEDED',
    notes: 'Fiberglass tanks do not corrode but can degrade. No CP needed but structural integrity monitoring recommended.',
  },
  {
    inspectionType: 'EPA_TANK_AGE_25_YEAR_ASSESSMENT',
    ruleSource: 'EPA',
    category: 'INSPECTION',
    frequencyMonths: null,
    frequencyDays: null,
    description:
      'Comprehensive assessment at the 25-year mark for all UST systems. Evaluate tank and piping integrity, corrosion protection effectiveness, release detection adequacy, and secondary containment status. Determine remaining useful life and upgrade needs.',
    citation: '40 CFR 280.21; EPA OUST Guidance',
    equipmentType: 'TANK',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'Milestone assessment. Many states require enhanced monitoring or closure planning for tanks exceeding 25-30 years.',
  },

  // ============================================
  // BIMONTHLY / QUARTERLY (frequencyMonths: 2-3)
  // ============================================
  {
    inspectionType: 'EPA_SACRIFICIAL_ANODE_CP_MONITORING',
    ruleSource: 'EPA',
    category: 'INSPECTION',
    frequencyMonths: null,
    frequencyDays: null,
    description:
      'Sacrificial (galvanic) anode cathodic protection systems do not require bimonthly inspections like impressed current systems, but must be included in the triennial CP survey (280.31(b)). Verify anode condition and adequate protection levels during survey.',
    citation: '40 CFR 280.31(b)',
    equipmentType: 'CATHODIC_PROTECTION',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: 'CATHODIC_PROTECTION',
    notes: 'Sacrificial anodes have finite life (typically 15-25 years). Unlike impressed current, no rectifier to check bimonthly. Triennial survey is the primary compliance check.',
  },
  {
    inspectionType: 'EPA_REMEDIATION_QUARTERLY_MONITORING',
    ruleSource: 'EPA',
    category: 'TESTING',
    frequencyMonths: 3,
    frequencyDays: null,
    description:
      'Quarterly groundwater and/or soil gas monitoring at sites with confirmed releases undergoing active remediation. Monitor contaminant concentrations, free product thickness, and remedy effectiveness. Results reported to implementing agency.',
    citation: '40 CFR 280.65-280.66',
    equipmentType: 'TANK',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'Applies only to facilities with confirmed releases under active corrective action. Frequency may increase to monthly based on agency direction.',
  },
  {
    inspectionType: 'EPA_ATG_DAILY_READING_VERIFICATION',
    ruleSource: 'EPA',
    category: 'INSPECTION',
    frequencyMonths: 1,
    frequencyDays: null,
    description:
      'Automatic tank gauging (ATG) systems must perform leak detection tests at least monthly per manufacturer specifications. Daily inventory data should be reviewed for anomalies. ATG must meet 0.2 gal/hr leak rate detection with 95% probability of detection.',
    citation: '40 CFR 280.43(a)',
    equipmentType: 'RELEASE_DETECTION',
    appliesToMaterial: null,
    appliesToLeakDetection: 'ATG',
    appliesToCorrosionProtection: null,
    notes: 'Most common modern leak detection method. ATG performs automated tests but operators must review results monthly. Equipment must meet NIST Handbook 44 standards.',
  },
  {
    inspectionType: 'EPA_ATG_ANNUAL_CALIBRATION',
    ruleSource: 'EPA',
    category: 'TESTING',
    frequencyMonths: 12,
    frequencyDays: null,
    description:
      'Annual calibration and operability verification of automatic tank gauging (ATG) system probes, sensors, and console per manufacturer specifications. Verify probe accuracy, water detection, and alarm functionality.',
    citation: '40 CFR 280.40(a)(3); 280.43(a)',
    equipmentType: 'RELEASE_DETECTION',
    appliesToMaterial: null,
    appliesToLeakDetection: 'ATG',
    appliesToCorrosionProtection: null,
    notes: 'Part of annual release detection operability testing. ATG-specific calibration ensures accurate inventory and leak detection.',
  },
  {
    inspectionType: 'EPA_PERIODIC_TIGHTNESS_TEST_PIPING',
    ruleSource: 'EPA',
    category: 'TESTING',
    frequencyMonths: 36,
    frequencyDays: null,
    description:
      'Suction piping that does not meet safe suction requirements (280.41(b)(2)(ii)) must be tested for tightness every 3 years. Pressurized piping with ALLD must also undergo periodic line tightness testing as secondary method.',
    citation: '40 CFR 280.44(b)',
    equipmentType: 'LINE_LEAK_DETECTOR',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'Safe suction piping (below-grade only, slopes to tank, one check valve) is exempt.',
  },
  {
    inspectionType: 'EPA_SECONDARY_CONTAINMENT_MONITORING',
    ruleSource: 'EPA',
    category: 'TESTING',
    frequencyMonths: 1,
    frequencyDays: null,
    description:
      'Interstitial monitoring of secondary containment (double-walled tanks and piping) must be conducted at least monthly. Monitoring records must be maintained.',
    citation: '40 CFR 280.43(g)',
    equipmentType: 'RELEASE_DETECTION',
    appliesToMaterial: null,
    appliesToLeakDetection: 'INTERSTITIAL_MONITORING',
    appliesToCorrosionProtection: null,
    notes: 'Required for all tanks/piping installed after April 11, 2016. Most common modern leak detection method.',
  },
  {
    inspectionType: 'EPA_MANUAL_TANK_GAUGING',
    ruleSource: 'EPA',
    category: 'TESTING',
    frequencyMonths: null,
    frequencyDays: 7,
    description:
      'Manual tank gauging: weekly measurements over a minimum 36-hour quiet period comparing product level changes against leak thresholds. Only permitted as sole method for tanks ≤2,000 gallons capacity.',
    citation: '40 CFR 280.43(b)',
    equipmentType: 'RELEASE_DETECTION',
    appliesToMaterial: null,
    appliesToLeakDetection: 'MANUAL_GAUGING',
    appliesToCorrosionProtection: null,
    notes: 'Tanks 551-1,000 gal: 0.5 gal/hr threshold. Tanks 1,001-2,000 gal: 1.0 gal/hr threshold. Not permitted for tanks >2,000 gallons.',
  },
  {
    inspectionType: 'EPA_SIR_ANALYSIS',
    ruleSource: 'EPA',
    category: 'TESTING',
    frequencyMonths: 1,
    frequencyDays: null,
    description:
      'Statistical inventory reconciliation (SIR) analysis performed monthly by a third-party vendor using daily inventory data. Must achieve minimum 0.2 gal/hr leak rate detection with 95% probability of detection and 5% false alarm rate.',
    citation: '40 CFR 280.43(c)',
    equipmentType: 'RELEASE_DETECTION',
    appliesToMaterial: null,
    appliesToLeakDetection: 'SIR',
    appliesToCorrosionProtection: null,
    notes: 'Requires at least 30 days of daily stick readings or ATG data. Must meet NIST Handbook 130.',
  },
  {
    inspectionType: 'EPA_GROUNDWATER_MONITORING',
    ruleSource: 'EPA',
    category: 'TESTING',
    frequencyMonths: 1,
    frequencyDays: null,
    description:
      'Groundwater monitoring wells must be checked at least monthly for presence of free product or dissolved contamination. Wells must be properly designed and placed in the excavation zone downgradient of the UST.',
    citation: '40 CFR 280.43(e)',
    equipmentType: 'RELEASE_DETECTION',
    appliesToMaterial: null,
    appliesToLeakDetection: 'GROUNDWATER_MONITORING',
    appliesToCorrosionProtection: null,
    notes: 'Groundwater must be within 20 feet of ground surface. Monitoring wells checked for free product per 280.43(e).',
  },
  {
    inspectionType: 'EPA_VAPOR_MONITORING',
    ruleSource: 'EPA',
    category: 'TESTING',
    frequencyMonths: 1,
    frequencyDays: null,
    description:
      'Vapor monitoring: monthly measurement of vapors in the soil gas around the UST system using monitoring wells or passive sensors. Must be able to detect vapors from any regulated substance stored.',
    citation: '40 CFR 280.43(d)',
    equipmentType: 'RELEASE_DETECTION',
    appliesToMaterial: null,
    appliesToLeakDetection: 'VAPOR_MONITORING',
    appliesToCorrosionProtection: null,
    notes: 'Backfill must be sufficiently porous. Stored substance must be volatile enough for vapor detection.',
  },

  // ============================================
  // EQUIPMENT MAINTENANCE (frequencyMonths: various)
  // ============================================
  {
    inspectionType: 'EPA_DISPENSER_CONTAINMENT_TEST',
    ruleSource: 'EPA',
    category: 'TESTING',
    frequencyMonths: 36,
    frequencyDays: null,
    description:
      'Under-dispenser containment (UDC) must be tested for liquid-tightness every 3 years. UDC systems collect releases at the dispenser and prevent product from reaching soil. Testing per PEI RP1200 or manufacturer specifications.',
    citation: '40 CFR 280.35(c)',
    equipmentType: 'CONTAINMENT_SUMP',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'Required by 2015 revision for dispensers installed after April 11, 2016. UDC testing is distinct from spill bucket testing.',
  },
  {
    inspectionType: 'EPA_SUCTION_PIPING_TIGHTNESS_TEST',
    ruleSource: 'EPA',
    category: 'TESTING',
    frequencyMonths: 36,
    frequencyDays: null,
    description:
      'Suction piping that does not meet safe suction criteria must undergo periodic tightness testing every 3 years. Safe suction piping (below-grade only, slopes to tank, single check valve at dispenser) is exempt from tightness testing and line leak detection.',
    citation: '40 CFR 280.41(b)(2)',
    equipmentType: 'LINE_LEAK_DETECTOR',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'Most gas stations use suction piping. Verify safe suction criteria annually during walkthrough. Non-safe suction piping requires triennial tightness test.',
  },
  {
    inspectionType: 'EPA_MONTHLY_INVENTORY_RECONCILIATION',
    ruleSource: 'EPA',
    category: 'DOCUMENTATION',
    frequencyMonths: 1,
    frequencyDays: null,
    description:
      'Monthly inventory control and reconciliation: compare product deliveries, sales, and tank readings to detect unexplained losses. Variance exceeding leak detection thresholds must be reported as suspected release. Records retained for 12 months minimum.',
    citation: '40 CFR 280.43(a)',
    equipmentType: 'RELEASE_DETECTION',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'Applies to all facilities as supplemental monitoring. Required as primary method when using SIR or manual gauging. ATG-equipped facilities must still reconcile inventory.',
  },
  {
    inspectionType: 'EPA_DELIVERY_DOCUMENTATION',
    ruleSource: 'EPA',
    category: 'DOCUMENTATION',
    frequencyMonths: null,
    frequencyDays: null,
    description:
      'Stick reading (manual measurement) or ATG reading required before and after each product delivery. Delivery ticket must be retained showing product type, quantity, date/time, and tank identification. Overfill prevention equipment must be verified operational before delivery.',
    citation: '40 CFR 280.35(a)(2); 280.30(a)',
    equipmentType: 'OVERFILL_PREVENTION',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'Delivery documentation is critical for inventory reconciliation and overfill prevention compliance.',
  },
  {
    inspectionType: 'EPA_EMERGENCY_RESPONSE_PLAN',
    ruleSource: 'EPA',
    category: 'DOCUMENTATION',
    frequencyMonths: 12,
    frequencyDays: null,
    description:
      'Annual review and update of facility emergency response procedures. Verify emergency contact numbers are current and posted, spill response equipment is available and functional, and Class C operators know emergency procedures. Maintain written emergency response plan.',
    citation: '40 CFR 280.244; 280.50',
    equipmentType: 'OPERATOR',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'Class C operator training covers emergency response. Annual plan review ensures contact info and procedures are current.',
  },
  {
    inspectionType: 'EPA_CP_TESTER_QUALIFICATION',
    ruleSource: 'EPA',
    category: 'CERTIFICATION',
    frequencyMonths: null,
    frequencyDays: null,
    description:
      'Cathodic protection system testing must be performed by a qualified cathodic protection tester meeting NACE International Cathodic Protection (CP) certification or equivalent. Verify tester credentials are current before each triennial survey.',
    citation: '40 CFR 280.31(b); NACE SP0169',
    equipmentType: 'CATHODIC_PROTECTION',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: 'CATHODIC_PROTECTION',
    notes: 'NACE CP1/CP2 certification typically renewed every 3-5 years. Facility must verify tester credentials.',
  },
  {
    inspectionType: 'EPA_FUEL_COMPATIBILITY_VERIFICATION',
    ruleSource: 'EPA',
    category: 'CERTIFICATION',
    frequencyMonths: null,
    frequencyDays: null,
    description:
      'Before storing a different regulated substance, verify compatibility of tank materials, linings, gaskets, seals, piping, and dispensing equipment with the new product. Particularly critical for ethanol blends (E15/E85), biodiesel, and alternative fuels which can degrade incompatible materials.',
    citation: '40 CFR 280.32; UL 2447',
    equipmentType: 'TANK',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'Required before any product change. UL listing or manufacturer certification of compatibility. E85 requires specifically rated components.',
  },
  {
    inspectionType: 'EPA_TANK_TIGHTNESS_TEST',
    ruleSource: 'EPA',
    category: 'TESTING',
    frequencyMonths: 60,
    frequencyDays: null,
    description:
      'Periodic tank tightness testing as alternative or supplemental leak detection method. Test must detect a leak rate of 0.1 gallon per hour with 95% probability of detection and 5% false alarm rate. Used as supplemental method with monthly inventory control for tanks ≤2,000 gallons.',
    citation: '40 CFR 280.43(c)',
    equipmentType: 'RELEASE_DETECTION',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'May be used as sole method for tanks ≤2,000 gal with manual gauging. For larger tanks, supplemental to ATG/SIR. Typically every 5 years.',
  },
  {
    inspectionType: 'EPA_ALLD_TRIENNIAL_FUNCTION_TEST',
    ruleSource: 'EPA',
    category: 'TESTING',
    frequencyMonths: 36,
    frequencyDays: null,
    description:
      'Triennial functional test of automatic line leak detectors (ALLDs) on pressurized piping. Verify mechanical shutoff valves, electronic sensors, and alarm systems activate at correct thresholds. More comprehensive than annual operability test.',
    citation: '40 CFR 280.44(a)',
    equipmentType: 'LINE_LEAK_DETECTOR',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'Supplements annual ALLD test. Triennial test must include full activation and shutoff verification per PEI RP100.',
  },
  {
    inspectionType: 'EPA_EXTERNAL_COATING_INSPECTION',
    ruleSource: 'EPA',
    category: 'INSPECTION',
    frequencyMonths: 60,
    frequencyDays: null,
    description:
      'Periodic inspection of external protective coatings (FRP coating, polyurethane, or factory-applied coating) on steel tanks when accessible during excavation, repair, or upgrade. Evaluate coating adhesion, thickness, and damage.',
    citation: '40 CFR 280.21(b)(3); NACE SP0169',
    equipmentType: 'TANK',
    appliesToMaterial: 'STEEL_WITH_FRP',
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'Steel tanks with FRP composite (STI-P3) rely on coating integrity for corrosion protection. Coating failure accelerates corrosion.',
  },
  {
    inspectionType: 'EPA_DOUBLE_WALL_ANNULAR_SPACE_TEST',
    ruleSource: 'EPA',
    category: 'TESTING',
    frequencyMonths: 36,
    frequencyDays: null,
    description:
      'Test integrity of double-walled tank annular (interstitial) space every 3 years to ensure the secondary wall is intact and monitoring is functional. Vacuum, pressure, or liquid-fill test per manufacturer specifications.',
    citation: '40 CFR 280.35(b); 280.43(g)',
    equipmentType: 'RELEASE_DETECTION',
    appliesToMaterial: null,
    appliesToLeakDetection: 'INTERSTITIAL_MONITORING',
    appliesToCorrosionProtection: null,
    notes: 'Applies to double-walled tanks and piping. Testing verifies both primary and secondary containment integrity.',
  },
  {
    inspectionType: 'EPA_SUBMERSIBLE_PUMP_CONTAINMENT_TEST',
    ruleSource: 'EPA',
    category: 'TESTING',
    frequencyMonths: 36,
    frequencyDays: null,
    description:
      'Test submersible turbine pump (STP) containment sumps every 3 years to ensure liquid-tightness. STP sumps contain piping connections below grade and must prevent releases from reaching soil.',
    citation: '40 CFR 280.35(b)',
    equipmentType: 'CONTAINMENT_SUMP',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'STP sumps are separate from spill buckets. Both require triennial testing under the 2015 revision.',
  },

  // ============================================
  // ONE-TIME / AS-NEEDED (frequencyMonths: null)
  // ============================================
  {
    inspectionType: 'EPA_RELEASE_CONFIRMATION',
    ruleSource: 'EPA',
    category: 'REPORTING',
    frequencyMonths: null,
    frequencyDays: 7,
    description:
      'Within 7 days of a suspected release, owner/operator must either confirm or rule out the release by conducting system tests, site checks, or secondary containment monitoring. If confirmed, full corrective action under Subpart F begins.',
    citation: '40 CFR 280.52',
    equipmentType: 'TANK',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'Distinct from 280.50 initial reporting. This is the investigation/confirmation step.',
  },
  {
    inspectionType: 'EPA_FREE_PRODUCT_REMOVAL',
    ruleSource: 'EPA',
    category: 'REPORTING',
    frequencyMonths: null,
    frequencyDays: null,
    description:
      'Upon confirmation of free product (LNAPL), begin removal as soon as practicable. Submit free product removal report to implementing agency within 45 days. Continue removal until free product is removed to the maximum extent practicable.',
    citation: '40 CFR 280.64',
    equipmentType: 'TANK',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'Free product removal is a distinct obligation from general corrective action. Must be continuous until complete.',
  },
  {
    inspectionType: 'EPA_SITE_CHARACTERIZATION',
    ruleSource: 'EPA',
    category: 'DOCUMENTATION',
    frequencyMonths: null,
    frequencyDays: null,
    description:
      'Conduct site characterization after confirmed release to define nature and extent of contamination. Install monitoring wells, collect soil/groundwater samples, and determine affected media. Submit site characterization report to implementing agency.',
    citation: '40 CFR 280.63',
    equipmentType: 'TANK',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'Typically within 60-90 days of confirmed release depending on state requirements. Defines scope of corrective action needed.',
  },
  {
    inspectionType: 'EPA_CORRECTIVE_ACTION_PLAN',
    ruleSource: 'EPA',
    category: 'DOCUMENTATION',
    frequencyMonths: null,
    frequencyDays: null,
    description:
      'Submit corrective action plan (CAP) to implementing agency for approval. Plan must describe selected remedy, implementation schedule, monitoring plan, and closure criteria. Remedy selection must consider cost-effectiveness and protectiveness.',
    citation: '40 CFR 280.66',
    equipmentType: 'TANK',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'Required for all confirmed releases requiring remediation beyond initial abatement. Agency approval required before implementing remedy.',
  },
  {
    inspectionType: 'EPA_REMEDIATION_PROGRESS_REPORTING',
    ruleSource: 'EPA',
    category: 'REPORTING',
    frequencyMonths: null,
    frequencyDays: null,
    description:
      'Periodic progress reports to implementing agency during active corrective action. Report remedy performance, monitoring results, and any modifications needed. Frequency typically annual or as directed by implementing agency.',
    citation: '40 CFR 280.67',
    equipmentType: 'TANK',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'Ongoing obligation for duration of remediation. Some cleanups last 5-20+ years.',
  },
  {
    inspectionType: 'EPA_TEMPORARY_CLOSURE_REQUIREMENTS',
    ruleSource: 'EPA',
    category: 'CLOSURE',
    frequencyMonths: 12,
    frequencyDays: null,
    description:
      'Temporarily closed UST systems must continue to meet release detection, corrosion protection, and release reporting requirements. If closure exceeds 12 months, permanent closure must be completed unless the implementing agency grants an extension.',
    citation: '40 CFR 280.70',
    equipmentType: 'TANK',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'Annual review required. Spill/overfill prevention may be deactivated if no product is delivered. Financial responsibility continues.',
  },
  {
    inspectionType: 'EPA_SECONDARY_CONTAINMENT_CERTIFICATION',
    ruleSource: 'EPA',
    category: 'CERTIFICATION',
    frequencyMonths: null,
    frequencyDays: null,
    description:
      'All new UST systems installed after April 11, 2016 must have secondary containment (double-walled tank and piping) with interstitial monitoring. Installer must certify secondary containment meets performance standards before system is placed into service.',
    citation: '40 CFR 280.20(c); 280.33',
    equipmentType: 'TANK',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: '2015 revision mandate. Pre-April 2016 single-walled systems grandfathered but encouraged to upgrade. Some states require retrofit.',
  },
  {
    inspectionType: 'EPA_SYSTEM_FAILURE_NOTIFICATION',
    ruleSource: 'EPA',
    category: 'REPORTING',
    frequencyMonths: null,
    frequencyDays: 1,
    description:
      'Notify implementing agency within 24 hours of any equipment failure that could cause a release, including release detection system malfunction, CP system failure, spill/overfill prevention failure, or containment breach.',
    citation: '40 CFR 280.50(a)',
    equipmentType: 'TANK',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'Distinct from release reporting. Equipment failure notification required even if no release is confirmed.',
  },
  {
    inspectionType: 'EPA_CLASS_C_TRAINING',
    ruleSource: 'EPA',
    category: 'TRAINING',
    frequencyMonths: null,
    frequencyDays: null,
    description:
      'Class C operator training must be completed before assuming duties. Class C operators are front-line employees responsible for responding to alarms, emergencies, and spills. Signage or written instructions can satisfy the requirement.',
    citation: '40 CFR 280.244',
    equipmentType: 'OPERATOR',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'Must be completed before the operator assumes duties. No periodic retraining required by federal rule (some states require it).',
  },
  {
    inspectionType: 'EPA_RELEASE_REPORTING_24HR',
    ruleSource: 'EPA',
    category: 'REPORTING',
    frequencyMonths: null,
    frequencyDays: 1,
    description:
      'Confirmed or suspected releases must be reported to the implementing agency within 24 hours. Includes unusual operating conditions, presence of free product, or failed leak detection tests.',
    citation: '40 CFR 280.50',
    equipmentType: 'TANK',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: null,
  },
  {
    inspectionType: 'EPA_SUSPECTED_RELEASE_INVESTIGATION',
    ruleSource: 'EPA',
    category: 'REPORTING',
    frequencyMonths: null,
    frequencyDays: 7,
    description:
      'Investigation of a suspected release must begin within 7 days. Owner/operator must perform system tests, site checks, and determine if contamination is present.',
    citation: '40 CFR 280.52',
    equipmentType: 'TANK',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: null,
  },
  {
    inspectionType: 'EPA_CORRECTIVE_ACTION_45DAY',
    ruleSource: 'EPA',
    category: 'REPORTING',
    frequencyMonths: null,
    frequencyDays: 45,
    description:
      'Initial corrective action steps must be completed within 45 days of a confirmed release. Includes free product removal, initial site characterization, and initial abatement measures.',
    citation: '40 CFR 280.62-280.65',
    equipmentType: 'TANK',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: null,
  },
  {
    inspectionType: 'EPA_NEW_TANK_NOTIFICATION',
    ruleSource: 'EPA',
    category: 'DOCUMENTATION',
    frequencyMonths: null,
    frequencyDays: null,
    description:
      'Notification of new UST system installation must be submitted to the implementing agency at least 30 days before installation begins. New installations after April 11, 2016 must have secondary containment with interstitial monitoring.',
    citation: '40 CFR 280.22, 280.20(c)',
    equipmentType: 'TANK',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: '2015 revision requires secondary containment for all new installations after April 11, 2016.',
  },
  {
    inspectionType: 'EPA_TANK_CLOSURE_NOTIFICATION',
    ruleSource: 'EPA',
    category: 'CLOSURE',
    frequencyMonths: null,
    frequencyDays: null,
    description:
      'Notification of permanent tank closure must be submitted to the implementing agency at least 30 days before closure begins. Must include closure plan, site assessment, and environmental sampling. Temporary closures exceeding 12 months must be permanently closed or receive an extension.',
    citation: '40 CFR 280.70-280.74',
    equipmentType: 'TANK',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'Temporary closure: 280.70. Permanent closure: 280.71. Site assessment: 280.72.',
  },
  {
    inspectionType: 'EPA_CHANGE_IN_SERVICE',
    ruleSource: 'EPA',
    category: 'DOCUMENTATION',
    frequencyMonths: null,
    frequencyDays: null,
    description:
      'Notification of change-in-service for a UST system. When a tank changes from storing a regulated substance, the owner must notify the implementing agency and comply with the same requirements as permanent closure.',
    citation: '40 CFR 280.71(c)',
    equipmentType: 'TANK',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: null,
  },
  // ============================================
  // DELIVERY PROHIBITION & ADMINISTRATIVE
  // ============================================
  {
    inspectionType: 'EPA_DELIVERY_PROHIBITION_CHECK',
    ruleSource: 'EPA',
    category: 'INSPECTION',
    frequencyMonths: 1,
    frequencyDays: null,
    description:
      'Monthly verification that facility is not subject to delivery prohibition. Delivery is prohibited when: spill prevention equipment is not in place or fails testing, overfill prevention is not installed or fails, release detection is not operational, owner/operator has not complied with temporary closure requirements, or registration/notification has not been completed. Verify compliance status before accepting deliveries.',
    citation: '40 CFR 280.11(d); Energy Policy Act §1526',
    equipmentType: 'TANK',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'Red/green tag system in most states. Non-compliance triggers delivery prohibition. Reinstatement requires demonstrating compliance.',
  },
  {
    inspectionType: 'EPA_FINANCIAL_MECHANISM_RENEWAL',
    ruleSource: 'EPA',
    category: 'FINANCIAL',
    frequencyMonths: 12,
    frequencyDays: null,
    description:
      'Annual renewal or verification of financial responsibility mechanism. Ensure insurance policy, surety bond, letter of credit, state fund coverage, or self-insurance meets current requirements ($1M per occurrence, $2M aggregate for most owners; $500K/$1M for facilities with <100 tanks). Verify coverage is continuous — any lapse triggers delivery prohibition.',
    citation: '40 CFR 280.90-280.116',
    equipmentType: 'FINANCIAL',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'Financial responsibility must be maintained without lapse. 60-day advance renewal recommended. Document mechanism type and expiration.',
  },
  {
    inspectionType: 'EPA_RECORDKEEPING_AUDIT',
    ruleSource: 'EPA',
    category: 'DOCUMENTATION',
    frequencyMonths: 12,
    frequencyDays: null,
    description:
      'Annual audit of required recordkeeping. Verify availability of: installation records, release detection records (last 12 months minimum), corrosion protection records, financial responsibility documentation, repair records, operator training records, closure records (if applicable), and recent compliance inspection results. Records must be maintained at the site or readily available for inspector review.',
    citation: '40 CFR 280.34; 280.36(b); 280.45',
    equipmentType: 'TANK',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'Release detection records: retain minimum 12 months. CP records: retain for life of system. Training records: retain as long as operator is designated.',
  },
  {
    inspectionType: 'EPA_OWNER_CHANGE_NOTIFICATION',
    ruleSource: 'EPA',
    category: 'REPORTING',
    frequencyMonths: null,
    frequencyDays: 30,
    description:
      'Notify implementing agency within 30 days of any change in ownership of UST system. Both previous and new owners must complete and submit notification forms. New owner must demonstrate financial responsibility before assuming ownership. Transfer of compliance history and pending corrective actions must be documented.',
    citation: '40 CFR 280.22; 280.34(a)',
    equipmentType: 'TANK',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'New owner inherits corrective action obligations. Financial responsibility must be in place before transfer.',
  },
  {
    inspectionType: 'EPA_INSTALLATION_CERTIFICATION',
    ruleSource: 'EPA',
    category: 'CERTIFICATION',
    frequencyMonths: null,
    frequencyDays: null,
    description:
      'Certification of proper installation for new or replacement UST systems. Installer must certify that tank and piping are installed per manufacturer instructions and industry codes (PEI RP100, API RP1615). Installation checklist includes: excavation inspection, backfill verification, containment testing, release detection activation, electrical grounding, and as-built documentation.',
    citation: '40 CFR 280.20(e)',
    equipmentType: 'TANK',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'One-time requirement per installation. Retain installation certification for life of tank.',
  },
  {
    inspectionType: 'EPA_REPAIR_DOCUMENTATION',
    ruleSource: 'EPA',
    category: 'DOCUMENTATION',
    frequencyMonths: null,
    frequencyDays: null,
    description:
      'Documentation and testing after any repair to UST system components. Repairs must follow manufacturer specifications or industry codes. Tanks repaired per API RP2200 or NACE standards. Piping repairs tested within 30 days. Cathodic protection tested within 6 months of repair. Spill/overfill equipment tested within 30 days of repair. Maintain records of all repairs.',
    citation: '40 CFR 280.33',
    equipmentType: 'TANK',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'Repair triggers retesting of affected components. Document repair method, date, contractor, and test results.',
  },
  {
    inspectionType: 'EPA_OPERATING_PROCEDURES_REVIEW',
    ruleSource: 'EPA',
    category: 'DOCUMENTATION',
    frequencyMonths: 12,
    frequencyDays: null,
    description:
      'Annual review of written operating procedures covering: fuel delivery and transfer, spill response, release detection monitoring, overfill prevention protocols, emergency shutdown, and routine maintenance schedules. Procedures must be current, accessible to all operators, and reflect actual equipment configuration at the facility.',
    citation: '40 CFR 280.31; 280.34',
    equipmentType: 'OPERATOR',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'Best practice per federal framework. Class C operators must have access to written emergency procedures.',
  },
  {
    inspectionType: 'EPA_PIPING_SECONDARY_CONTAINMENT_TEST',
    ruleSource: 'EPA',
    category: 'TESTING',
    frequencyMonths: 36,
    frequencyDays: null,
    description:
      'Triennial integrity testing of pressurized piping secondary containment systems. Double-wall piping interstice, piping containment sumps, and trench liners must be tested to verify liquid-tightness. Testing methods include vacuum, pressure, or hydrostatic per PEI RP1200 or equivalent.',
    citation: '40 CFR 280.35(a)(1)(ii); 280.44',
    equipmentType: 'SECONDARY_CONTAINMENT',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'Required for pressurized piping with secondary containment. Supplements 280.44 piping release detection.',
  },
  {
    inspectionType: 'EPA_OVERFILL_PREVENTION_INSPECTION',
    ruleSource: 'EPA',
    category: 'INSPECTION',
    frequencyMonths: 36,
    frequencyDays: null,
    description:
      'Triennial inspection of overfill prevention equipment. Verify ball float valves, flapper valves, or electronic shutoff devices are functional. Check alarm systems activate at proper levels (90% for high-level alarm, 95% for automatic shutoff). Inspect for corrosion, mechanical damage, or obstruction.',
    citation: '40 CFR 280.35(a)(2)',
    equipmentType: 'OVERFILL_PREVENTION',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'Added by 2015 UST rule revision. Compliance date: Oct 13, 2018.',
  },
  {
    inspectionType: 'EPA_UNDER_DISPENSER_CONTAINMENT_TEST',
    ruleSource: 'EPA',
    category: 'TESTING',
    frequencyMonths: 36,
    frequencyDays: null,
    description:
      'Triennial integrity testing of under-dispenser containment (UDC). Required for all new and replaced dispensers (since 2015 rule). Verify UDC is liquid-tight using vacuum, pressure, or hydrostatic testing per PEI RP1200 or manufacturer specifications. Inspect sensors/probes for proper function.',
    citation: '40 CFR 280.20(c)(2); 280.35',
    equipmentType: 'CONTAINMENT_SUMP',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'UDC required for all dispensers installed after 2015 revision. Existing dispensers: required when replaced.',
  },
  {
    inspectionType: 'EPA_ALTERNATIVE_FUEL_COMPATIBILITY',
    ruleSource: 'EPA',
    category: 'DOCUMENTATION',
    frequencyMonths: null,
    frequencyDays: null,
    description:
      'Compatibility demonstration required before storing alternative fuels (E15+, biodiesel blends >B20, other non-traditional fuels). Owner must demonstrate that entire UST system (tank, piping, containment, dispensers, seals, gaskets) is compatible with stored substance. Acceptable methods: manufacturer approval, third-party listing (UL), or engineering assessment.',
    citation: '40 CFR 280.32',
    equipmentType: 'TANK',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'One-time per fuel type transition. Must be redone if fuel blend changes. Critical for E15/E85 conversions.',
  },
  {
    inspectionType: 'EPA_TEMPORARY_CLOSURE_MAINTENANCE',
    ruleSource: 'EPA',
    category: 'INSPECTION',
    frequencyMonths: 1,
    frequencyDays: null,
    description:
      'Monthly maintenance requirements during temporary closure. Continue release detection and corrosion protection operations. Cap and secure fill pipes, gauge openings, and pump fittings. If temporarily closed >3 months, release detection is not required only if tank is empty. Temporary closure exceeding 12 months requires permanent closure or approved extension.',
    citation: '40 CFR 280.70',
    equipmentType: 'TANK',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'Temporary closure cannot exceed 12 months without extension. All other compliance requirements continue during temporary closure.',
  },
  {
    inspectionType: 'EPA_CLOSURE_SITE_ASSESSMENT',
    ruleSource: 'EPA',
    category: 'CLOSURE',
    frequencyMonths: null,
    frequencyDays: null,
    description:
      'Site assessment required at permanent closure. Collect soil and groundwater samples from the excavation zone to verify no contamination. If contamination is detected, begin corrective action per Subpart F. Assessment report must be submitted to implementing agency. Sampling protocol per state guidelines or EPA SW-846 methods.',
    citation: '40 CFR 280.72',
    equipmentType: 'TANK',
    appliesToMaterial: null,
    appliesToLeakDetection: null,
    appliesToCorrosionProtection: null,
    notes: 'Closure report must document site conditions. Contamination triggers Subpart F corrective action.',
  },
];
