/**
 * Blog seed — 12 SEO article stubs for the TankGuard content engine.
 *
 * Each entry sets slug + title + excerpt + meta tags + category + tags.
 * The `content` field is intentionally a generation placeholder; the
 * weekly `pnpm seo:generate` script (scripts/generate-seo-article.ts)
 * picks up rows where content === SEO_PLACEHOLDER_BODY and fills them
 * via the Anthropic API.
 *
 * Run:   pnpm tsx prisma/seed-blog.ts
 *
 * Idempotent: uses upsert on slug, so re-running is safe and won't
 * duplicate stubs. To regenerate a body, delete the row's content
 * (or re-run the SEO generator with --force).
 */

import { PrismaClient } from '../src/generated/prisma';

const prisma = new PrismaClient();

const SEO_PLACEHOLDER_BODY =
  '{{TODO_GENERATE}} — body to be generated by scripts/generate-seo-article.ts. ' +
  'Use the article brief in metaDescription as the prompt seed; target 1,200-1,800 words; ' +
  'include H2 sections, an early CTA to /register, and a closing CTA to the relevant tier ' +
  'landing block. Cite the federal CFR or state code wherever a compliance fact is asserted.';

interface BlogStub {
  slug: string;
  title: string;
  excerpt: string;
  metaTitle: string;
  metaDescription: string;
  category: string;
  tags: string[];
}

// Articles target the highest-converting TankGuard ICP buckets:
// (1) multi-station operators in strict-enforcement states (FL/CA/NJ/IN/NY/TX),
// (2) single-station owners post-violation, (3) compliance rule deep-dives.
const ARTICLES: BlogStub[] = [
  {
    slug: 'ust-compliance-multi-station-operators',
    title: 'UST Compliance for Multi-Station Operators: A Field Guide',
    excerpt:
      'Running 2-10 stations means juggling overlapping monthly, quarterly, triennial, and annual deadlines across different jurisdictions. Here is how multi-station operators stay audit-ready without hiring a full-time compliance lead.',
    metaTitle: 'UST Compliance for Multi-Station Operators | TankGuard',
    metaDescription:
      'How owners of 2-10 gas stations track overlapping EPA + state UST compliance deadlines across jurisdictions. Operator class training, release detection, financial responsibility, and what changes when each new station gets added to the portfolio.',
    category: 'Multi-Station Operations',
    tags: ['multi-station', 'compliance', 'EPA', 'state-rules'],
  },
  {
    slug: 'epa-40-cfr-part-280-simplified',
    title: 'EPA 40 CFR Part 280 Simplified: What UST Owners Actually Need to Know',
    excerpt:
      'The federal UST regulation runs 200+ pages. Owners need maybe 20 of them. We break down the operating, monitoring, recordkeeping, and reporting obligations that drive 90% of inspection findings.',
    metaTitle: 'EPA 40 CFR Part 280 Simplified for UST Owners | TankGuard',
    metaDescription:
      'Plain-English walkthrough of EPA 40 CFR Part 280 — the federal UST rule. Operating + monitoring obligations, release detection methods, financial responsibility, recordkeeping requirements, and the violations that drive most inspection failures.',
    category: 'Federal Regulations',
    tags: ['EPA', '40 CFR 280', 'federal', 'compliance-101'],
  },
  {
    slug: 'florida-ust-compliance-checklist',
    title: 'Florida UST Compliance Checklist: Monthly Self-Inspections, FL DEP Audits, and the Backlog That Won\'t Quit',
    excerpt:
      'Florida is the most aggressively-enforced UST jurisdiction in the country: monthly operator self-inspections, FL DEP on-site audits, and a 7,856-release cleanup backlog. Here is the deadline-by-deadline checklist for FL operators.',
    metaTitle: 'Florida UST Compliance Checklist | TankGuard',
    metaDescription:
      'FL DEP UST compliance checklist for gas station owners. Monthly operator self-inspection requirements, annual line/leak detection certifications, triennial CP testing, and the documentation FL inspectors look for first.',
    category: 'State Compliance',
    tags: ['Florida', 'FL DEP', 'monthly-inspection', 'state-rules'],
  },
  {
    slug: 'california-single-wall-tank-closure-deadlines',
    title: 'California Single-Wall Tank Closure: What the Deadline Actually Means for Your Stations',
    excerpt:
      'California has the strictest UST regime in the country and the largest active-inspection program (13,383/year). The single-wall tank closure deadline reshapes which tanks you can keep operating. Here is what owners need to do, and by when.',
    metaTitle: 'California Single-Wall UST Closure Deadlines | TankGuard',
    metaDescription:
      'CA SWRCB single-wall UST closure timeline, exemption criteria, and what counts as compliant replacement equipment. Designed for owners running 1-10 stations across CA who need a clear deadline calendar without a $5,000/yr environmental consultant.',
    category: 'State Compliance',
    tags: ['California', 'CA SWRCB', 'closure', 'state-rules'],
  },
  {
    slug: 'new-jersey-ust-3-year-inspection-cycle',
    title: 'New Jersey\'s 3-Year UST Inspection Cycle: The Document Trail That Keeps NJ DEP Happy',
    excerpt:
      'NJ DEP runs UST inspections on a strict 3-year cycle and cleanup costs run $50k-$1M+ when something is missed. The inspectors care about documentation as much as the tank itself. Here is what to keep, and where.',
    metaTitle: 'New Jersey UST 3-Year Inspection Cycle | TankGuard',
    metaDescription:
      'NJ DEP underground storage tank 3-year inspection cycle requirements. The document vault every NJ operator needs, the most-cited NJ violations, and how the 4,784-release backlog drives current enforcement priorities.',
    category: 'State Compliance',
    tags: ['New Jersey', 'NJ DEP', 'inspection-cycle', 'state-rules'],
  },
  {
    slug: 'indiana-ust-compliance-lowest-in-nation',
    title: 'Indiana Has the Lowest UST Compliance Rate in the Nation. Here Is Why That Matters for Your Stations.',
    excerpt:
      'Indiana\'s Technical Compliance Rate is 19% — meaning 81% of inspected facilities fail. IDEM is raising enforcement funding. If you operate USTs in IN, the next 18 months will be unforgiving for sites that aren\'t already ahead of the schedule.',
    metaTitle: 'Indiana UST Compliance: 81% Failure Rate | TankGuard',
    metaDescription:
      'IDEM is the most-failed UST inspector in the country (19% Technical Compliance Rate). What IN operators need on file before the next inspection: release detection records, operator training, financial responsibility certs, and corrosion-protection testing.',
    category: 'State Compliance',
    tags: ['Indiana', 'IDEM', 'enforcement', 'state-rules'],
  },
  {
    slug: 'new-york-dec-pbs-requirements',
    title: 'New York DEC Petroleum Bulk Storage Requirements: A Walkthrough for Multi-Site Owners',
    excerpt:
      'NY DEC oversees 7,681 UST facilities under the Petroleum Bulk Storage program. The registration, tightness-testing, and corrosion-protection requirements stack differently than the EPA federal baseline. Here is the New York-specific overlay.',
    metaTitle: 'NY DEC PBS Requirements for UST Owners | TankGuard',
    metaDescription:
      'New York DEC Petroleum Bulk Storage program requirements for owners of underground storage tanks. PBS registration, tightness testing schedules, corrosion protection certifications, and the NY-specific recordkeeping that goes beyond federal 40 CFR 280.',
    category: 'State Compliance',
    tags: ['New York', 'NY DEC', 'PBS', 'state-rules'],
  },
  {
    slug: 'texas-tceq-ust-program',
    title: 'Texas TCEQ UST Program: What 16,504 Convenience Stores Need to Know',
    excerpt:
      'Texas has the largest convenience-store base in the country (16,504 sites). TCEQ administers the UST program with moderate enforcement but massive scale. Here is the TX-specific compliance map for owners running 2-10 stations.',
    metaTitle: 'Texas TCEQ UST Compliance Guide | TankGuard',
    metaDescription:
      'TCEQ underground storage tank requirements for Texas convenience-store and gas-station operators. Annual self-inspections, release detection options approved in TX, financial responsibility documentation, and the closure-in-place vs removal decision tree.',
    category: 'State Compliance',
    tags: ['Texas', 'TCEQ', 'PST', 'state-rules'],
  },
  {
    slug: 'operator-class-a-b-c-training-requirements',
    title: 'Operator Class A, B, and C Training: What Each Class Actually Has to Know',
    excerpt:
      'EPA requires designated operators in three classes — A (overall responsibility), B (day-to-day operations), C (emergency response). The certification, retraining, and recordkeeping rules differ by state. Here is the per-class breakdown.',
    metaTitle: 'UST Operator Class A/B/C Training Requirements | TankGuard',
    metaDescription:
      'EPA-required Class A, B, and C UST operator training and certification requirements. State-by-state retraining cadence, approved training providers (per state), what inspectors verify, and the recordkeeping that satisfies an audit on the spot.',
    category: 'Operator Training',
    tags: ['operator-training', 'class-A', 'class-B', 'class-C', 'EPA'],
  },
  {
    slug: 'release-detection-methods-compared',
    title: 'Release Detection Methods Compared: ATG, SIR, Manual Gauging, and the Trade-offs Inspectors Care About',
    excerpt:
      'EPA approves several release-detection methods (Automatic Tank Gauging, Statistical Inventory Reconciliation, manual gauging, interstitial monitoring, vapor monitoring, groundwater monitoring). Each has cost, accuracy, and recordkeeping trade-offs. Here is how to choose.',
    metaTitle: 'UST Release Detection Methods Compared | TankGuard',
    metaDescription:
      'Compare ATG, SIR, manual gauging, interstitial, vapor, and groundwater monitoring for UST release detection. Cost, false-alarm rates, recordkeeping burden, what works for single-walled vs double-walled tanks, and how each method holds up under EPA + state inspection.',
    category: 'Equipment & Methods',
    tags: ['release-detection', 'ATG', 'SIR', 'monitoring'],
  },
  {
    slug: 'after-a-failed-ust-inspection',
    title: 'After a Failed UST Inspection: A 30-Day Action Plan for Owners',
    excerpt:
      'Roughly 30,000 stations fail UST inspections every year. The first 30 days after a Notice of Violation determine whether the path is a corrected operating permit or a delivery prohibition. Here is the day-by-day playbook.',
    metaTitle: 'What to Do After a Failed UST Inspection | TankGuard',
    metaDescription:
      '30-day action plan for UST owners who just received a Notice of Violation or failed an inspection. Documenting the response, working with the implementing agency, avoiding a delivery-prohibition order, and preventing the second-violation escalation that triggers per-day fines.',
    category: 'Enforcement Response',
    tags: ['violations', 'enforcement', 'notice-of-violation', 'recovery'],
  },
  {
    slug: 'financial-responsibility-mechanisms-for-ust-owners',
    title: 'Financial Responsibility for UST Owners: Insurance, Trust Funds, and the State Programs Most Operators Don\'t Know About',
    excerpt:
      'Federal and state rules require UST owners to demonstrate financial responsibility for cleanup and third-party damages — typically $1M per occurrence. Insurance, surety bonds, state trust funds, and self-insurance each have different costs and approval paths.',
    metaTitle: 'UST Financial Responsibility Requirements | TankGuard',
    metaDescription:
      'How UST owners satisfy federal financial responsibility requirements: commercial insurance, surety bonds, letters of credit, state trust funds, and self-insurance. Per-state coverage thresholds, required documentation, and the audit trail that keeps the implementing agency satisfied.',
    category: 'Financial Responsibility',
    tags: ['financial-responsibility', 'insurance', 'state-trust-funds'],
  },
];

async function main() {
  console.log(`Seeding ${ARTICLES.length} blog stubs (idempotent upsert by slug)...`);
  let created = 0;
  let skipped = 0;

  for (const stub of ARTICLES) {
    const existing = await prisma.blogPost.findUnique({ where: { slug: stub.slug } });
    if (existing && existing.content && !existing.content.startsWith('{{TODO_GENERATE}}')) {
      // Body already generated — leave it alone.
      skipped += 1;
      continue;
    }

    await prisma.blogPost.upsert({
      where: { slug: stub.slug },
      update: {
        title: stub.title,
        excerpt: stub.excerpt,
        metaTitle: stub.metaTitle,
        metaDescription: stub.metaDescription,
        category: stub.category,
        tags: stub.tags,
      },
      create: {
        slug: stub.slug,
        title: stub.title,
        excerpt: stub.excerpt,
        content: SEO_PLACEHOLDER_BODY,
        author: 'TankGuard Team',
        category: stub.category,
        tags: stub.tags,
        published: false,
        metaTitle: stub.metaTitle,
        metaDescription: stub.metaDescription,
      },
    });
    created += 1;
  }

  console.log(`Done. Stubs upserted: ${created}. Generated bodies left untouched: ${skipped}.`);
  console.log(
    'Next: run `pnpm seo:generate` to fill bodies for each stub (script reads ' +
      'metaDescription as the prompt seed and updates BlogPost.content).',
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
